Repository subhadip-saha-05/Python-Voice-Assistant, pull requests merged in 2023-01, with the labels that each got.

#29 Added the feature play
  jarvis.py
Labels: SWOC23, Easy

#37 Added social media platforms and OTT platforms #1
  jarvis.py
Labels: SWOC23, Easy

#39 Fix Error for Linux
  Setup.sh
  jarvis.py
Labels: SWOC23, Easy

#42 Add some AmazingFeature
  jarvis.py
Labels: SWOC23, Easy

#49 Update jarvis.py With Translation Feature
  jarvis.py
Labels: SWOC23, Easy

#52 Update jarvis.py Battery Display Feature
  jarvis.py
Labels: SWOC23, Easy

#61 Setting Alarm, How to Command and System Status added
  jarvis.py
  tempCodeRunnerFile.py
Labels: SWOC23, Easy

#70 Fix requirements.txt + Update installation scripts
  README.md
  Setup.bat
  Setup.sh
  requirements.txt
Labels: SWOC23, Beginner

#82 Feature/updation
  LICENSE
  README.md
Labels: SWOC23, Beginner

#81 Refactored code with addition of name
  .idea/.gitignore
  .idea/Python-Voice-Assistant.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  jarvis.py
  requirements.txt
Labels: SWOC23, Medium
